// Package Openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Service defines model for Service.
type Service struct {
	DefinitionPath *string `json:"definitionPath,omitempty"`
	Name           *string `json:"name,omitempty"`
	Version        *string `json:"version,omitempty"`
}

// RegisterServiceJSONBody defines parameters for RegisterService.
type RegisterServiceJSONBody Service

// RegisterServiceRequestBody defines body for RegisterService for application/json ContentType.
type RegisterServiceJSONRequestBody RegisterServiceJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A callback for modifying requests which are generated before sending over
	// the network.
	RequestEditor RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = http.DefaultClient
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditor = fn
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RegisterService request  with any body
	RegisterServiceWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error)

	RegisterService(ctx context.Context, body RegisterServiceJSONRequestBody) (*http.Response, error)
}

func (c *Client) RegisterServiceWithBody(ctx context.Context, contentType string, body io.Reader) (*http.Response, error) {
	req, err := NewRegisterServiceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterService(ctx context.Context, body RegisterServiceJSONRequestBody) (*http.Response, error) {
	req, err := NewRegisterServiceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if c.RequestEditor != nil {
		err = c.RequestEditor(ctx, req)
		if err != nil {
			return nil, err
		}
	}
	return c.Client.Do(req)
}

// NewRegisterServiceRequest calls the generic RegisterService builder with application/json body
func NewRegisterServiceRequest(server string, body RegisterServiceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterServiceRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterServiceRequestWithBody generates requests for RegisterService with any type of body
func NewRegisterServiceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	queryUrl, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	basePath := fmt.Sprintf("/register")
	if basePath[0] == '/' {
		basePath = basePath[1:]
	}

	queryUrl, err = queryUrl.Parse(basePath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryUrl.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)
	return req, nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RegisterService request  with any body
	RegisterServiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*RegisterServiceResponse, error)

	RegisterServiceWithResponse(ctx context.Context, body RegisterServiceJSONRequestBody) (*RegisterServiceResponse, error)
}

type RegisterServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r RegisterServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RegisterServiceWithBodyWithResponse request with arbitrary body returning *RegisterServiceResponse
func (c *ClientWithResponses) RegisterServiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader) (*RegisterServiceResponse, error) {
	rsp, err := c.RegisterServiceWithBody(ctx, contentType, body)
	if err != nil {
		return nil, err
	}
	return ParseRegisterServiceResponse(rsp)
}

func (c *ClientWithResponses) RegisterServiceWithResponse(ctx context.Context, body RegisterServiceJSONRequestBody) (*RegisterServiceResponse, error) {
	rsp, err := c.RegisterService(ctx, body)
	if err != nil {
		return nil, err
	}
	return ParseRegisterServiceResponse(rsp)
}

// ParseRegisterServiceResponse parses an HTTP response from a RegisterServiceWithResponse call
func ParseRegisterServiceResponse(rsp *http.Response) (*RegisterServiceResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer rsp.Body.Close()
	if err != nil {
		return nil, err
	}

	response := &RegisterServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// registerService
	// (POST /register)
	RegisterService(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// RegisterService converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterService(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterService(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/register", wrapper.RegisterService)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5xTT2/bPgz9KgJ/v6Mbe/8wwLeuxYAchmZtb8MOqszEKiRRE+k0QeDvPkiu12TJaTeB",
	"pB/fe3w+gCEfKWAQhvYAbHr0ujwfMG2twfyMiSImsVgaHa5tsGIprLT0uSL7iNACS7JhA2MFQXu82Nhi",
	"YkvhQm+sQKy4XJo3V/MMPT2jERjzkA1rmliwSTZKQYPH3rK6Xi2VZTUwdkpIJdxYFkyKJzxWOpQG7iIx",
	"qoyUvM4ISj/RIEp69AuowFmDgYuCSQk83t3eQQVDctBCLxLbuhbqaGHIwzl1dU9D3ny9WsKRaHi3aBZN",
	"nqeIQUcLLXwopQqilr7YW8+8i/PEcq72flamVcCXWR8U2FQELbujsTc/E/4akOULdfuMaigIhrJAx+is",
	"Kd/WzzxdaApDfv2fcA0t/Fe/paV+jUo9o5frnPKc3Zjud3yTVy42YQetpAHHXOBIgaeQvW+avxgK7qSO",
	"Ttt/4zZW8LH5dO7lMmy1s52yIQ5SYsiD9zrtoYV0ZuDu6o/FV4wiNmwK3Wvn6OV2H7S35islv9JJexRM",
	"DO1aO8bqZOT7gGl/YeaGnEMjFzpL/jY4sTeTHw+SUPv830z9SV/OQfnmx+E0qY6Mdj2xtJ+bpoHx5/g7",
	"AAD//2GXyY34AwAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
